title: Joy Theme Documentation
description: Developer documentation for the Joy Shopify theme
theme: just-the-docs

url: https://etempa-web-solutions.github.io/Joy-Theme-Documentation/

aux_links:
  Template Repository: https://github.com/Etempa-Web-Solutions/Joy-Theme-Documentation
